### ISSUE TITLE
Pending at specific times

### ISSUE THREAD

**Issue by semidirect** [uchicago-cs/cs121-officehours-webapp#23] opened 2020-10-05 20:43 UTC
Based on my experience last autumn, it would be useful to be able to see just pending request from people available in a specific time slot. This is currently possible  for the current time slot (in the "Pending Now" tab), but I recall that the "Pending Today" tab also doesn't quite provide this.

**Comment by borjasotomayor** [comment] 2020-10-05 20:54
Closing as this is a duplicate of #6

**Closed as completed by borjasotomayor** 2020-10-05 20:54 UTC

**Comment by semidirect** [comment] 2020-10-05 21:00
Sorry! I did scan the older issues but I overlooked it.
